rvm:
- 2.2.7
- 2.3.4
- 2.4.1
services:
- redis-server
env:
  global:
    - CC_TEST_REPORTER_ID=c6e51bc4755c4602fccb935a436625bbac4be498193c4f40ba8c8e2ee0745182
sudo: false
language: ruby
cache: bundler
before_install: gem install bundler -v 1.15.4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

