# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)

require 'rubygems'
require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])
require 'fileutils'
require 'rspec/its'

require 'simplecov'
SimpleCov.start

require 'turnstile'

require_relative 'support/logging'

RSpec.configure do |config|
  config.order = 'random'

  config.before :all  do
    Turnstile::RSpec::Logging.configure
  end

  config.before :each do
    Turnstile::Adapter.new.redis.flushdb
  end

  config.around :each, logging: true do |ex|
    Turnstile::Logger.enable
    Turnstile::Logger.enable

    Turnstile::Logger.info_elapsed('measuring example: ') do
      ex.run
    end
    Turnstile::Logger.disable
  end
end
